version: '3'
services:
        web:
                image: twenty3_port
                build: .
                ports:
                        - "8023:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
