version: '3'
services:
        web:
                image: ourshiny_flask
                build: .
                ports:
                        - "8723:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
