version: '3'
services:
        web:
                image: flask_23_v1
                build: .
                ports:
                        - "8040:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
